language: node_js
node_js:
- "4"
sudo: false
script: npm run $COMMAND
env:
  matrix:
  - COMMAND=test
branches:
  only:
  - master
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
